apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-local
  labels:
    app: guestbook-local
spec:
  selector:
    matchLabels:
      app: guestbook-local
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook-local
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: docker-registry:5000/frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: reg-cred-secret
