apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort   
  ports:
    - nodePort: 31111
      port: 80
  selector:
    app: guestbook
    tier: frontend
