apiVersion: v1
kind: Service
metadata:
  name: frontend-local
  labels:
    app: guestbook-local
    tier: frontend
spec:
  type: NodePort   
  ports:
    - nodePort: 31115
      port: 80
  selector:
    app: guestbook-local
    tier: frontend
