apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-local-master
  labels:
    app: redis-local
spec:
  selector:
    matchLabels:
      app: redis-local
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-local
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: docker-registry:5000/redismaster:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
      imagePullSecrets:
      - name: reg-cred-secret

